CREATE TABLE `changeRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`crId` varchar(50) NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`requestedBy` varchar(200),
	`requestedById` int,
	`assignedTo` varchar(200),
	`assignedToId` int,
	`priority` varchar(50) DEFAULT 'Medium',
	`crStatus` enum('Draft','Submitted','Under Review','Approved','Rejected','Implemented','Closed') NOT NULL DEFAULT 'Draft',
	`impactAssessment` text,
	`requirementId` varchar(50),
	`taskId` varchar(50),
	`issueId` varchar(50),
	`submittedAt` timestamp,
	`reviewedAt` timestamp,
	`approvedAt` timestamp,
	`implementedAt` timestamp,
	`reviewedBy` varchar(200),
	`approvedBy` varchar(200),
	`rejectionReason` text,
	`estimatedEffort` varchar(100),
	`actualEffort` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `changeRequests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `decisions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`decisionId` varchar(50) NOT NULL,
	`meetingId` int,
	`title` varchar(255) NOT NULL,
	`description` text,
	`decisionDate` date NOT NULL,
	`decidedBy` varchar(200),
	`decidedById` int,
	`decisionStatus` enum('Open','Implemented','Deferred','Cancelled') NOT NULL DEFAULT 'Open',
	`impact` varchar(100),
	`requirementId` varchar(50),
	`taskId` varchar(50),
	`issueId` varchar(50),
	`actionItems` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `decisions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meetings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`meetingId` varchar(50) NOT NULL,
	`title` varchar(255) NOT NULL,
	`meetingDate` date NOT NULL,
	`startTime` varchar(10),
	`endTime` varchar(10),
	`location` varchar(255),
	`organizer` varchar(200),
	`organizerId` int,
	`attendees` json,
	`agenda` text,
	`minutes` text,
	`meetingStatus` enum('Scheduled','In Progress','Completed','Cancelled') NOT NULL DEFAULT 'Scheduled',
	`nextMeetingDate` date,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meetings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `taskDependencies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`predecessorTaskId` varchar(50) NOT NULL,
	`successorTaskId` varchar(50) NOT NULL,
	`dependencyType` enum('Finish-to-Start','Start-to-Start','Finish-to-Finish','Start-to-Finish') NOT NULL DEFAULT 'Finish-to-Start',
	`lagDays` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `taskDependencies_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `testCases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`testId` varchar(50) NOT NULL,
	`requirementId` varchar(50),
	`title` varchar(255) NOT NULL,
	`description` text,
	`preconditions` text,
	`testSteps` json,
	`expectedResult` text,
	`actualResult` text,
	`tester` varchar(200),
	`testerId` int,
	`priority` varchar(50) DEFAULT 'Medium',
	`testStatus` enum('Not Executed','In Progress','Passed','Failed','Blocked','Skipped') NOT NULL DEFAULT 'Not Executed',
	`testType` varchar(100),
	`executionDate` date,
	`defectId` varchar(50),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `testCases_id` PRIMARY KEY(`id`)
);
